# -*- coding: utf-8 -*-
"""Copy of thaicons.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tZVze6LsaMkxiXWVdsAPPSk1o06C3_Nw
"""

import tkinter as tk
from random import shuffle

# List of Thai consonants and their pronunciation
thai_consonants = [
    ("ก", "gor gai (ก ไก่)"),
    ("\u0e02", "khor khai (ข ไข่)"),
    ("\u0e03", "khor khuad (ฃ ขวด)"),
    ("\u0e04", "khor khwai (ค ควาย)"),
    ("\u0e05", "khor khon (ฅ คน)"),
    ("\u0e06", "khor rakhang (ฆ ระฆัง)"),
    ("\u0e07", "ngor ngu (ง งู)"),
    ("\u0e08", "jor jan (จ จาน)"),
    ("\u0e09", "chor ching (ฉ ฉิ่ง)"),
    ("\u0e0a", "chor chang (ช ช้าง)")
]
shuffle(thai_consonants)

class FlashcardApp:
    def __init__(self, root):
        self.root = root
        self.root.title("Thai Consonant Flashcards")
        self.root.geometry("400x300")
        self.index = 0
        self.flipped = False

        self.card_frame = tk.Frame(self.root, bd=2, relief=tk.RIDGE)
        self.card_frame.pack(expand=True, fill=tk.BOTH, padx=20, pady=20)

        self.label = tk.Label(self.card_frame, text=thai_consonants[self.index][0], font=("Arial", 50))
        self.label.pack(expand=True, fill=tk.BOTH)

        self.button_frame = tk.Frame(self.root)
        self.button_frame.pack(fill=tk.X, pady=10)

        self.prev_button = tk.Button(self.button_frame, text="Previous", command=self.previous_card)
        self.prev_button.pack(side=tk.LEFT, expand=True)

        self.flip_button = tk.Button(self.button_frame, text="Flip", command=self.flip_card)
        self.flip_button.pack(side=tk.LEFT, expand=True)

        self.next_button = tk.Button(self.button_frame, text="Next", command=self.next_card)
        self.next_button.pack(side=tk.LEFT, expand=True)

    def flip_card(self):
        self.flipped = not self.flipped
        if self.flipped:
            self.label.config(text=thai_consonants[self.index][1], font=("Arial", 20))
        else:
            self.label.config(text=thai_consonants[self.index][0], font=("Arial", 50))

    def next_card(self):
        self.index = (self.index + 1) % len(thai_consonants)
        self.flipped = False
        self.label.config(text=thai_consonants[self.index][0], font=("Arial", 50))

    def previous_card(self):
        self.index = (self.index - 1) % len(thai_consonants)
        self.flipped = False
        self.label.config(text=thai_consonants[self.index][0], font=("Arial", 50))

if __name__ == "__main__":
    root = tk.Tk()
    app = FlashcardApp(root)
    root.mainloop()